### ISSUE TITLE
[Features/Suggestions] Command Style recode

### ISSUE THREAD

**Issue by mkcoldwolf** [filoghost/HolographicDisplays#125]
the command for this plugins is really horrible for my opinion
like each time you will have to do /hd create {Name}
so that each time when u want to edit a hologram
u will have to rewrite the code or just many backwards key 
that is really annoying especially when u naming ur hologram well and the name is long.
i hope u guys can kinda rewrite it into style like PermissionEX
/hd {Name} create
or /hd edit {name} addline MyLine
{name} before action somethings like that
or keep both style of command

That would really easier to manage those hologram, thanks for listening!

**Comment by filoghost** [comment]
I've added a way to quickly modify a hologram after changing one of its lines: https://github.com/filoghost/HolographicDisplays/commit/c0da957d6c103a25c2986b115de97a549f6af735

Changing the order of the commands now would confuse some users, and it's not beneficial if you only need to edit one line (because the commands becomes longer).
