### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Andre601** [filoghost/HolographicDisplays#130]
## Issue
My server crashed out of nowhere and after a restart does HolographicDisplays now throw this error here: https://paste.helpch.at/rojicamiwe.css

## Additional information.
Server: PaperSpigot git-Paper-1478 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugins: https://paste.helpch.at/osirukekac
Threat dump of the crash: https://paste.helpch.at/kahizasiki.sql

According to my host do they run OpenJ9 since a month (roughly)
The console provides this information on startup:
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190205_213 (JIT enabled, AOT enabled)
OpenJ9 - 90dd8cb40
OMR - d2f4534b
JCL - d002501a90 based on jdk8u202-b08)
```

**Comment by Andre601** [comment]
[412]: https://dev.bukkit.org/projects/holographic-displays/issues/412
[414]: https://dev.bukkit.org/projects/holographic-displays/issues/414
[415]: https://dev.bukkit.org/projects/holographic-displays/issues/415
[417]: https://dev.bukkit.org/projects/holographic-displays/issues/417
[418]: https://dev.bukkit.org/projects/holographic-displays/issues/418

Multiple people on dev.bukkit report the same issues

Report-#[412]
Report-#[414]
Report-#[415]
Report-#[417]
Report-#[418]

**Comment by sgdc3** [comment]
@Andre601 What's your HolographicDisplays version?

**Comment by Andre601** [comment]
Latest release which at this point is 2.3.2

**Comment by sgdc3** [comment]
try to use the latest dev build from ci.filoghost.net

**Comment by Andre601** [comment]
I tried latest from the jenkins (2.3.3) but still receive this error.

**Comment by filoghost** [comment]
The error in reality is just a warning. The plugin works just fine, it means it cannot use a feature to speed up some things. It has been now disabled and will only show up in debug mode: https://github.com/filoghost/HolographicDisplays/commit/87fc7bde5ae889abb817ba853fefbcb0a4022e61

**Comment by Andre601** [comment]
Okay. Thanks for that.

But what exactly causes this? Like I assume it's a missing thing that perhaps could be related to the server using OpenJ9?
Would really love to know what causes this and what could be a solution for the future.

**Comment by filoghost** [comment]
I think it's because some versions of OpenJDK block the use of java's internal API methods, and the plugin cannot "see" or use them, or they simply renamed them. There is the default method that only uses the public API, but is a bit slower since it does some useless calculations for the scope of HD.

It shouldn't have any real impact on performance, and there were no complaints before the new method was implemented.

**Comment by filoghost** [comment]
I think it's because some versions of OpenJDK block the use of java's internal API methods, and the plugin cannot "see" or use them, or they simply renamed them. There is the default method that only uses the public API, but is a bit slower since it does some useless calculations for the scope of HD.

It shouldn't have any real impact on performance, and there were no complaints before the new method was implemented.
