### ISSUE TITLE
Visibility Permission Restrictions

### ISSUE THREAD

**Issue by ArctoranDev** [filoghost/HolographicDisplays#340]
### Description
I would really like to use this idea where specific holographic displays are only visible to players if they have a permission to actually view the holographic display.

**Comment by PLG** [comment]
Also permission related; it would be interesting to set a permission for each hologram created e.g., holograms.access.NAME. So that it is possible to limit a user from teleporting to only certain holograms. This would mimic the functionality that Multiverse portals has: https://github.com/Multiverse/Multiverse-Core/wiki/Permissions-%28Portals%29

The same permission could be used to limit visibility as the OP suggested.

**Comment by filoghost** [comment]
Kind of late, but I won't be implementing this, sorry. Use https://www.spigotmc.org/resources/phd.77631/
