### ISSUE TITLE
registerPlaceholder method API

### ISSUE THREAD

**Issue by Darkool** [filoghost/HolographicDisplays#35]
Hello filoghost, I have an issue **registerPlaceholder** allows to create a new placeholder like %playername% ? 
so How I can use it to create a placeholder for example %faction% I have method myfaction.getfactioname(Player p) that returns a string. I want to avoid individual holograms

HologramsAPI.registerPlaceholder(plugin, textPlaceholder, refreshRate, replacer) 

Thanks in advance.

**Comment by filoghost** [comment]
What do you mean by "personal hologram"? You can't have individual placeholders however.

**Comment by Darkool** [comment]
%playername% works as placeholder and every player can see her own name on the hologram, It's possible create my own placeHolder? and show it like your placeholders on holographic displays?

**Comment by filoghost** [comment]
It's internal, it doesn't has an API and requires Protocol Lib. You could try doing the same (look at the code).

**Comment by sgdc3** [comment]
> It's internal
That's why an API would be nice ;)

**Comment by filoghost** [comment]
It would be dependent on Protocol Lib, and also any placeholder that is not really fast would cause problems.

**Comment by sgdc3** [comment]
@filoghost la dipendenza da plib non mi sembra un problema, ricordiamoci che si tratterebbe di una funzionalità aggiuntiva. Il problema della velocità vale in ogni campo, non puoi usare questa cosa come scusa xD

**Comment by filoghost** [comment]
Please keep the original language. Having a major problem there would slow packets, and it probably wouldn't be easy to identify the problem with timings. For normal placeholders, you can see from timings that the PlaceholderManager is causing lag. Also, it would be an API relying on another API, and people would start complaining that it doesn't work (because they don't have ProtocolLib).

**Comment by sgdc3** [comment]
Non arrampicarti sugli specchi, il fatto è che a te non serve questa feature, e lo comprendo. Miraccomando però, non aspettare che hd venga superato da qualche obrobrio a pagamento.

**Comment by filoghost** [comment]
Non mi sto arrampicando sugli specchi, ho spiegato esattamente i motivi che non mi spingono a farlo. Quello, più il tempo che non ho.

**Comment by sgdc3** [comment]
Se ti serve una mano per tentare di ottimizzare il packet listener io e gli altri membri del team di authme possiamo aiutarti.

**Comment by filoghost** [comment]
Anche risolto il problema della velocità, rimangono gli altri.

**Comment by sgdc3** [comment]
Ci saranno sempre problemi, ma si risolvono. Non essere pessimista. Con authme è ormai un anno che stiamo ristrutturando l'indtero progetto, ogni volta che incapsuliamo qualcosa molte features su buggano  e causa problemi di performance, ma non ci siamo mai arresi e continuiamo tuttora sperado ad un certo punto di poter offrire un prodotto migliore.

**Comment by filoghost** [comment]
Non sono problemi risolvibili, parlo dell'API che dipende da un'altra API. Anche se facessi tutto giusto, mi arriverebbero comunque bug report di persone che non hanno installato ProtocolLib o hanno messo una versione sbagliata.

**Comment by sgdc3** [comment]
Filo, esiste il "ma vai a quel paese" come risposta ai rompiscatole, funziona sempre ;)

**Comment by sgdc3** [comment]
E te lo dice uno che riceve più del triplo delle richieste sul tracker

**Comment by filoghost** [comment]
After thinking about this, I've decided to deny the request. The main reason is that individual placeholders:
1) depend on another plugin that is not strictly required
2) they are not a stable feature, they could be removed in the future
3) lag caused by bad implementations by other developers (this is already the case for normal placeholders, but in the future there will be a method to update the placeholder. Plugins will not have to implement an interface returning a String at fixed intervals)
