### ISSUE TITLE
Too much consume on timmings

### ISSUE THREAD

**Issue by UnitedCraft** [filoghost/HolographicDisplays#598]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/holographic-displays/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/HolographicDisplays) of Holographic Displays and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/HolographicDisplays/issues?q=is%3Aissue).

### Description

How can I prevent from using so much CPU?
![image](https://user-images.githubusercontent.com/79587189/159117856-669f132e-5c50-4298-b950-e8748ef98672.png)

### How to reproduce

1. 50 holograms without rainbow effect

### Server version

1.18.2 purpur

### Holographic Displays version

The laster build 205

### Installed plugins that allow players to join with multiple Minecraft versions

ViaVersion, ViaBackwards

**Comment by jurienhamaker** [comment]
Can confirm the same issue:
![image](https://user-images.githubusercontent.com/5418114/160020654-ef15841b-2065-473b-ba46-8281ff024556.png)

**How to reproduce**
46 holograms without rainbow effect

**Server version**
1.18.1 paper

**Holographic Displays version**
3.0.0 Beta 2

Installed plugins that allow players to join with multiple Minecraft versions
ViaVersion

**Comment by HexedHero** [comment]
Having the same issues, not even that many holograms and using zero placeholders outside of &u

**Comment by filoghost** [comment]
Does this still happen with the latest versions? I tried spawning many holograms locally, but it doesn't seem to impact performance like that. I have no clue what causes it in particular, and I don't think I can optimize the code further.

**Comment by w4sb0y** [comment]
Still quite a large amount of cpu usage on 1.18.2
![image](https://github.com/filoghost/HolographicDisplays/assets/68382177/2e82f818-1a1c-4aa4-a675-dbe76fd742a3)

**Comment by filoghost** [comment]
I don't see anything too weird here, since sending packets is how the plugin works. Possibly there are some placeholders which are updating frequently, causing many packets to be sent? Maybe the packets should be sent from a different thread, as a solution? Not sure if it's even allowed. But given that I will stop maintaining the plugin the end of this month, I don't think it's worth the effort.

**Comment by filoghost** [comment]
Just checked, it seems that sending packets async is possible, but I'm not sure of the implications or if it does cause race conditions or concurrency issues (which are extremely hard to find and debug).
Might try one last patch before stopping the maintenance.

**Comment by filoghost** [comment]
I've made a quick (and ugly) change for async packets with the latest dev build.

Be aware that this is a highly experimental build, might have some unintended bugs. When you make the code run async, especially in Bukkit/Spigot, it might cause some race conditions, hard to reproduce and debug.

My personal tip is just to do yourself a favor and switch to another plugin, rather than use this build, which is a temporary fix since the plugin will not be maintained. If you want to try it: https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by Xaziss** [comment]
thank you for your service o7
